// The one place the dashboard takes its icons from (lucide-react, pinned in
// package.json). Pages import from here, never from lucide-react directly, so
// the set the app uses stays small, named consistently and easy to audit.
// Where lucide renamed an icon, the familiar name is kept as the export.
export {
  ArrowRight,
  BookOpen,
  Brain,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDashed,
  CircleCheck,
  CircleX,
  Clapperboard,
  Film,
  Gift,
  Image as ImageIcon,
  Info,
  LayoutDashboard,
  Lightbulb,
  Lock,
  MapPin,
  Mic,
  MoreHorizontal,
  Monitor,
  Package,
  Palette,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Settings,
  SlidersHorizontal,
  Sparkles,
  Users,
  Volume2,
  Ban,
  CircleDollarSign,
  X,
  ArrowDownToLine,
  Bot,
  Copy,
  Cpu,
  Dot,
  Eye,
  EyeOff,
  FastForward,
  FileText,
  Flag,
  Gauge,
  KeyRound,
  Link as LinkIcon,
  Menu as MenuIcon,
  OctagonX,
  Repeat,
  Save,
  Server,
  SkipForward,
  Timer,
  User,
  Wallet,
  Wrench,
  Trash as Trash2,
  TriangleAlert as AlertTriangle,
  LoaderCircle as Loader2,
  WandSparkles as Wand2,
} from 'lucide-react'
