"""Build the fruitstory ComfyUI workflow templates (API format) from Python.

The JSON files next to this script are generated by ``python -m fruitstory.workflows._build``;
edit this file, not the JSON. Each template follows the repo's ``comfy_workflow_v1`` shape
(``graph`` in ComfyUI API format, literal inputs replaced by ``{{placeholders}}``) plus:

- ``files``: placeholders that name an uploaded input file (image, audio);
- ``derived``: placeholders the renderer computes (``frames``, ``half_width`` ...), see
  :mod:`fruitstory.comfy_templates`;
- ``output_node`` / ``last_frame_node``: where the clip and its last frame come out.

Sources (read 2026-10-08):
- ``ltx25_i2v_speech``: Comfy-Org/workflow_templates ``video_ltx2_5_i2v.json`` (subgraph flattened).
- ``ltx25_a2v_speech``: Lightricks/ComfyUI-LTXVideo ``2.5/LTX-2.5_A2V_Two_Stage_Distilled.json``
  (its custom-node prompt switches dropped: core nodes only).
- ``ltx23_idlora_speech``: Comfy-Org/workflow_templates ``video_ltx2_3_id_lora.json``.
- ``tts_chatterbox_line``: Comfy-Org ``audio-chatterbox_tts_multilingual.json`` + ComfyUI_Fill-ChatterBox
  (the pack pinned in docker/worker-comfyui-tts; the repo's ``tts_chatterbox.json`` template is the
  app's equivalent).

Every node class used here exists in ComfyUI 0.34.0 (the version pinned by worker-comfyui
5.10.0); ``fruitstory/tools/validate_workflows.py`` checks that against the ComfyUI source.
"""

from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Distilled schedules of the official templates.
SIGMAS_8_STEP = "1.0, 0.99375, 0.9875, 0.98125, 0.975, 0.909375, 0.725, 0.421875, 0.0"
SIGMAS_STAGE2_I2V = "0.85, 0.7250, 0.4219, 0.0"          # LTX-2.5 I2V and LTX-2.3 ID-LoRA templates
SIGMAS_STAGE2_A2V = "0.909375, 0.725, 0.421875, 0.0"     # LTX-2.5 A2V template

NEGATIVE_DEFAULT = ("live action, real people, photograph, human skin, mask, costume, "
                    "blurry, deformed mouth, extra limbs, text, subtitles, watermark, pc game, "
                    "console game, video game, childish, ugly")

LTX25 = {
    "unet": "ltx-2.5-22b-distilled-transformer-comfy-int8-convrot.safetensors",
    "clip": "gemma4-12b-with-proj-ltx-2.5-comfy-int8-convrot.safetensors",
    "vae": "ltx-2.5-video-vae-bf16.safetensors",
    "audio_vae": "ltx-2.5-audio-vae-bf16.safetensors",
    "upscaler": "ltx-2.5-latent-spatial-upscaler-x2-bf16-1.0.safetensors",
}
LTX23 = {
    "ckpt": "ltx-2.3-22b-dev-fp8.safetensors",
    "text_encoder": "gemma_3_12B_it_fp4_mixed.safetensors",
    "distilled_lora": "ltx_2.3_22b_distilled_1.1_lora_dynamic_fro09_avg_rank_111_bf16.safetensors",
    "id_lora": "ltx-2.3-id-lora-talkvid-3k.safetensors",
    "upscaler": "ltx-2.3-spatial-upscaler-x2-1.1.safetensors",
}


def node(class_type: str, **inputs) -> dict:
    return {"class_type": class_type, "inputs": inputs}


def link(node_id: str, slot: int = 0) -> list:
    return [node_id, slot]


# ----------------------------------------------------------------- shared blocks

def _image_in(graph: dict) -> None:
    """LoadImage -> ImageScale (center crop to the clip size) -> LTXVPreprocess."""
    graph["image"] = node("LoadImage", image="{{image}}")
    graph["scale"] = node("ImageScale", image=link("image"), upscale_method="lanczos",
                          width="{{width}}", height="{{height}}", crop="center")
    graph["prep"] = node("LTXVPreprocess", image=link("scale"), img_compression=18)


def _video_out(graph: dict, vae: list, audio: list, *, tiled=(512, 64, 64, 16)) -> None:
    """VAEDecodeTiled -> CreateVideo(+audio) -> SaveVideo (mp4/h264), plus the last frame as PNG.

    Core ``SaveVideo`` reports its file under the ``images`` history key, the only key the
    stock worker-comfyui handler returns; ``SaveImage`` of the last frame arrives in the
    same array (used as the continuity reference of the next shot).
    """
    tile_size, overlap, temporal_size, temporal_overlap = tiled
    graph["dec"] = node("VAEDecodeTiled", samples=link("sep2"), vae=vae, tile_size=tile_size, overlap=overlap,
                        temporal_size=temporal_size, temporal_overlap=temporal_overlap)
    graph["video"] = node("CreateVideo", images=link("dec"), fps="{{fps}}", audio=audio)
    graph["save"] = {"class_type": "SaveVideo",
                     "inputs": {"video": link("video"), "filename_prefix": "fruitstory/{{name}}",
                                "format": "mp4", "format.codec": "h264"}}
    graph["last"] = node("ImageFromBatch", image=link("dec"), batch_index="{{last_index}}", length=1)
    graph["save_last"] = node("SaveImage", images=link("last"), filename_prefix="fruitstory/{{name}}_last")


def _two_stage(graph: dict, *, model1: list, model2: list, pos1: list, neg1: list, pos2: list, neg2: list,
               vae: list, audio_latent1: list, audio_latent2, guider: str, sampler: str,
               sigmas2: str, cfg_inputs: dict) -> None:
    """Stage 1 at half size (8 distilled steps) -> x2 latent upsampler -> stage 2 (3 steps).

    ``audio_latent2`` is a link, or ``"stage1"`` to reuse the audio latent stage 1 produced.
    """
    graph["lat1"] = node("EmptyLTXVLatentVideo", width="{{half_width}}", height="{{half_height}}",
                         length="{{frames}}", batch_size=1)
    graph["i2v1"] = node("LTXVImgToVideoInplace", vae=vae, image=link("prep"), latent=link("lat1"),
                         strength=0.7, bypass=False)
    graph["cat1"] = node("LTXVConcatAVLatent", video_latent=link("i2v1"), audio_latent=audio_latent1)
    graph["guider1"] = node(guider, model=model1, positive=pos1, negative=neg1, **cfg_inputs)
    graph["noise1"] = node("RandomNoise", noise_seed="{{seed}}")
    graph["sampler"] = node("KSamplerSelect", sampler_name=sampler)
    graph["sig1"] = node("ManualSigmas", sigmas=SIGMAS_8_STEP)
    graph["s1"] = node("SamplerCustomAdvanced", noise=link("noise1"), guider=link("guider1"),
                       sampler=link("sampler"), sigmas=link("sig1"), latent_image=link("cat1"))
    graph["sep1"] = node("LTXVSeparateAVLatent", av_latent=link("s1"))
    graph["ups"] = node("LTXVLatentUpsampler", samples=link("sep1", 0), upscale_model=link("up_model"), vae=vae)
    graph["i2v2"] = node("LTXVImgToVideoInplace", vae=vae, image=link("prep"), latent=link("ups"),
                         strength=1.0, bypass=False)
    graph["cat2"] = node("LTXVConcatAVLatent", video_latent=link("i2v2"),
                         audio_latent=link("sep1", 1) if audio_latent2 == "stage1" else audio_latent2)
    graph["guider2"] = node(guider, model=model2, positive=pos2, negative=neg2, **cfg_inputs)
    graph["noise2"] = node("RandomNoise", noise_seed=42)
    graph["sig2"] = node("ManualSigmas", sigmas=sigmas2)
    graph["s2"] = node("SamplerCustomAdvanced", noise=link("noise2"), guider=link("guider2"),
                       sampler=link("sampler"), sigmas=link("sig2"), latent_image=link("cat2"))
    graph["sep2"] = node("LTXVSeparateAVLatent", av_latent=link("s2"))


def _ltx25_loaders(graph: dict) -> None:
    graph["unet"] = node("UNETLoader", unet_name=LTX25["unet"], weight_dtype="default")
    graph["vae"] = node("VAELoader", vae_name=LTX25["vae"])
    graph["avae"] = node("VAELoader", vae_name=LTX25["audio_vae"])
    graph["clip"] = node("CLIPLoader", clip_name=LTX25["clip"], type="ltxv", device="default")
    graph["up_model"] = node("LatentUpscaleModelLoader", model_name=LTX25["upscaler"])
    graph["pos"] = node("CLIPTextEncode", text="{{prompt}}", clip=link("clip"))
    graph["neg"] = node("CLIPTextEncode", text="{{negative}}", clip=link("clip"))
    graph["cond"] = node("LTXVConditioning", positive=link("pos"), negative=link("neg"), frame_rate="{{fps}}")


def _template(name: str, task: str, description: str, graph: dict, placeholders: list, files: dict,
              requires: list, **extra) -> dict:
    tpl = {
        "$schema": "comfy_workflow_v1",
        "name": name,
        "task": task,
        "core_nodes_only": extra.pop("core_nodes_only", True),
        "verified_live": False,
        "description": description,
        "placeholders": placeholders,
        "files": files,
        "derived": {"frames": "1 + floor(fps * seconds / 8) * 8", "half_width": "width / 2",
                    "half_height": "height / 2", "last_index": "frames - 1"},
        "defaults": {"width": 704, "height": 1280, "fps": 24, "seconds": 5, "negative": NEGATIVE_DEFAULT},
        "frame_rule": {"fps": 24, "frame_step": 8, "max_frames": 241, "lengths": [5, 6, 8, 10]},
        "requires": requires,
        "output_node": "save",
        "last_frame_node": "save_last",
        "graph": graph,
    }
    tpl.update(extra)
    return tpl


def _req(node_id: str, field: str, file: str, folder: str) -> dict:
    return {"node": node_id, "field": field, "file": file, "dir": f"models/{folder}"}


# ----------------------------------------------------------------- the four templates

def ltx25_i2v_speech() -> dict:
    """Path (a): LTX-2.5 image-to-video, dialogue spoken from the prompt alone (joint audio)."""
    g: dict = {}
    _image_in(g)
    _ltx25_loaders(g)
    g["alat"] = node("LTXVEmptyLatentAudio", audio_vae=link("avae"), frames_number="{{frames}}",
                     frame_rate="{{fps}}", batch_size=1)
    _two_stage(g, model1=link("unet"), model2=link("unet"), pos1=link("cond", 0), neg1=link("cond", 1),
               pos2=link("cond", 0), neg2=link("cond", 1), vae=link("vae"), audio_latent1=link("alat"),
               audio_latent2="stage1", guider="LTXVDualCFGGuider", sampler="euler_ancestral",
               sigmas2=SIGMAS_STAGE2_I2V, cfg_inputs={"video_cfg": 1.0, "audio_cfg": 1.0})
    g["adec"] = node("LTXVAudioVAEDecode", samples=link("sep2", 1), audio_vae=link("avae"))
    _video_out(g, vae=link("vae"), audio=link("adec"))
    return _template(
        "ltx25_i2v_speech", "i2v_speech",
        "LTX-2.5 22B distilled int8, two-stage (8 steps at half size, x2 latent upscale, 3 steps), "
        "24 fps, joint audio: the character speaks the quoted line of the prompt with a voice the prompt "
        "describes. The clip is saved WITH its sound (mp4/h264+aac) and its last frame as PNG. "
        "Authored from ComfyUI's video_ltx2_5_i2v.json (2026-10-08), subgraph flattened, prompt "
        "enhancer dropped. Only core nodes of ComfyUI 0.34.0.",
        g, ["image", "prompt", "negative", "seed", "width", "height", "seconds", "fps", "name"],
        {"image": "the keyframe (png), uploaded as input.images[].name"},
        [_req("unet", "unet_name", LTX25["unet"], "diffusion_models"),
         _req("clip", "clip_name", LTX25["clip"], "text_encoders"),
         _req("vae", "vae_name", LTX25["vae"], "vae"),
         _req("avae", "vae_name", LTX25["audio_vae"], "vae"),
         _req("up_model", "model_name", LTX25["upscaler"], "latent_upscale_models")],
    )


def ltx25_a2v_speech() -> dict:
    """Path (b): LTX-2.5 audio-to-video from a keyframe: the line's audio (TTS in the character's
    locked voice) is encoded, frozen in both stages and muxed back unchanged; the model performs
    lips, breath and body to it."""
    g: dict = {}
    _image_in(g)
    _ltx25_loaders(g)
    g["audio"] = node("LoadAudio", audio="{{audio}}")
    g["trim"] = node("TrimAudioDuration", audio=link("audio"), start_index=0.0, duration="{{seconds}}")
    g["aenc"] = node("LTXVAudioVAEEncode", audio=link("trim"), audio_vae=link("avae"))
    g["mask"] = node("SolidMask", value=0.0, width=1024, height=1024)
    g["frozen"] = node("SetLatentNoiseMask", samples=link("aenc"), mask=link("mask"))
    _two_stage(g, model1=link("unet"), model2=link("unet"), pos1=link("cond", 0), neg1=link("cond", 1),
               pos2=link("cond", 0), neg2=link("cond", 1), vae=link("vae"), audio_latent1=link("frozen"),
               audio_latent2=link("frozen"), guider="CFGGuider", sampler="{{sampler}}",
               sigmas2=SIGMAS_STAGE2_A2V, cfg_inputs={"cfg": 1.0})
    _video_out(g, vae=link("vae"), audio=link("trim"))
    tpl = _template(
        "ltx25_a2v_speech", "a2v_speech",
        "LTX-2.5 22B distilled int8 audio-to-video, two-stage: the uploaded line audio is trimmed to "
        "`seconds`, encoded by the audio VAE and frozen (noise mask 0) through both stages; the "
        "original waveform is muxed into the mp4. Sampler `euler` by default (the ancestral sampler "
        "and modality guidance are what the community reports as breaking lip-sync on 2.5, HF "
        "discussion #44); CFG 1. Authored from ComfyUI-LTXVideo 2.5/LTX-2.5_A2V_Two_Stage_Distilled.json "
        "(2026-10-08) with its API/enhancer switches removed: only core nodes of ComfyUI 0.34.0.",
        g, ["image", "audio", "prompt", "negative", "seed", "width", "height", "seconds", "fps", "sampler", "name"],
        {"image": "the keyframe (png)", "audio": "the line's audio (wav/mp3), uploaded like an image"},
        [_req("unet", "unet_name", LTX25["unet"], "diffusion_models"),
         _req("clip", "clip_name", LTX25["clip"], "text_encoders"),
         _req("vae", "vae_name", LTX25["vae"], "vae"),
         _req("avae", "vae_name", LTX25["audio_vae"], "vae"),
         _req("up_model", "model_name", LTX25["upscaler"], "latent_upscale_models")],
    )
    tpl["defaults"]["sampler"] = "euler"
    tpl["derived"]["seconds"] = "audio duration + 0.7 s tail, rounded up to the frame rule (set by the runner)"
    return tpl


def ltx23_idlora_speech() -> dict:
    """Path (c): LTX-2.3 ID-LoRA, one generation: keyframe + ~5 s reference voice -> the character
    speaks the [SPEECH] text with that voice (native LTXVReferenceAudio node)."""
    g: dict = {}
    _image_in(g)
    g["ckpt"] = node("CheckpointLoaderSimple", ckpt_name=LTX23["ckpt"])
    g["te"] = node("LTXAVTextEncoderLoader", text_encoder=LTX23["text_encoder"], ckpt_name=LTX23["ckpt"],
                   device="default")
    g["avae"] = node("LTXVAudioVAELoader", ckpt_name=LTX23["ckpt"])
    g["lora_d"] = node("LoraLoaderModelOnly", model=link("ckpt", 0), lora_name=LTX23["distilled_lora"],
                       strength_model=0.5)
    g["lora_id"] = node("LoraLoaderModelOnly", model=link("lora_d"), lora_name=LTX23["id_lora"], strength_model=1.0)
    g["up_model"] = node("LatentUpscaleModelLoader", model_name=LTX23["upscaler"])
    g["pos"] = node("CLIPTextEncode", text="{{prompt}}", clip=link("te"))
    g["neg"] = node("CLIPTextEncode", text="{{negative}}", clip=link("te"))
    g["refaudio"] = node("LoadAudio", audio="{{voice_ref}}")
    g["ref"] = node("LTXVReferenceAudio", model=link("lora_id"), positive=link("pos"), negative=link("neg"),
                    reference_audio=link("refaudio"), audio_vae=link("avae"),
                    identity_guidance_scale="{{identity_guidance}}", start_percent=0.0, end_percent=1.0)
    g["cond"] = node("LTXVConditioning", positive=link("ref", 1), negative=link("ref", 2), frame_rate="{{fps}}")
    g["alat"] = node("LTXVEmptyLatentAudio", audio_vae=link("avae"), frames_number="{{frames}}",
                     frame_rate="{{fps}}", batch_size=1)
    # Stage 1 samples the ID-LoRA model with the reference-audio conditioning; stage 2 refines with
    # the distilled LoRA only, its conditioning cropped to the stage-1 latent (as the official template).
    g["crop"] = node("LTXVCropGuides", positive=link("cond", 0), negative=link("cond", 1), latent=link("sep1", 0))
    _two_stage(g, model1=link("ref", 0), model2=link("lora_d"), pos1=link("cond", 0), neg1=link("cond", 1),
               pos2=link("crop", 0), neg2=link("crop", 1), vae=link("ckpt", 2), audio_latent1=link("alat"),
               audio_latent2="stage1", guider="CFGGuider", sampler="euler",
               sigmas2=SIGMAS_STAGE2_I2V, cfg_inputs={"cfg": 1.0})
    g["adec"] = node("LTXVAudioVAEDecode", samples=link("sep2", 1), audio_vae=link("avae"))
    _video_out(g, vae=link("ckpt", 2), audio=link("adec"), tiled=(768, 64, 4096, 4))
    tpl = _template(
        "ltx23_idlora_speech", "idlora_speech",
        "LTX-2.3 22B dev fp8 + distilled LoRA 0.5 + ID-LoRA (TalkVid) 1.0, two-stage, 24 fps. The "
        "reference voice (~5 s wav) conditions the model through the native LTXVReferenceAudio node; "
        "the prompt uses the [VISUAL]/[SPEECH]/[SOUNDS] sections. Authored from ComfyUI's "
        "video_ltx2_3_id_lora.json (2026-10-08), subgraph flattened. Only core nodes of ComfyUI 0.34.0.",
        g, ["image", "voice_ref", "prompt", "negative", "seed", "width", "height", "seconds", "fps",
            "identity_guidance", "name"],
        {"image": "the keyframe (png)", "voice_ref": "the character's locked voice reference (wav, 5-10 s)"},
        [_req("ckpt", "ckpt_name", LTX23["ckpt"], "checkpoints"),
         _req("te", "text_encoder", LTX23["text_encoder"], "text_encoders"),
         _req("lora_d", "lora_name", LTX23["distilled_lora"], "loras"),
         _req("lora_id", "lora_name", LTX23["id_lora"], "loras"),
         _req("up_model", "model_name", LTX23["upscaler"], "latent_upscale_models")],
    )
    tpl["defaults"]["identity_guidance"] = 3.0
    return tpl


def tts_chatterbox_line() -> dict:
    """One spoken line in a character's locked voice (Chatterbox Multilingual, 5-10 s reference).

    Core ``SaveAudio`` writes a flac; the repo's worker image (docker/worker-comfyui-tts) patches
    the handler to return it under the ``audio`` key, which :mod:`fruitstory.runpod_client` reads.
    """
    g: dict = {}
    g["ref"] = node("LoadAudio", audio="{{voice_ref}}")
    g["tts"] = node("FL_ChatterboxMultilingualTTS", text="{{text}}", language="{{language}}",
                    exaggeration="{{exaggeration}}", cfg_weight=0.5, temperature=0.8, repetition_penalty=2.0,
                    min_p=0.05, top_p=1.0, seed="{{seed}}", audio_prompt=link("ref"), use_cpu=False,
                    keep_model_loaded=True)
    g["save"] = node("SaveAudio", audio=link("tts", 0), filename_prefix="fruitstory/{{name}}")
    return {
        "$schema": "comfy_workflow_v1",
        "name": "tts_chatterbox_line",
        "task": "tts_line",
        "core_nodes_only": False,
        "custom_nodes": ["comfyui_fill-chatterbox"],
        "verified_live": False,
        "description": "Chatterbox Multilingual TTS (23 languages incl. French) cloning the character's "
                       "reference voice for one line, saved as flac by core SaveAudio and returned under the "
                       "`audio` key by the repo's patched worker handler (docker/worker-comfyui-tts). Language "
                       "values are the node's labels, e.g. 'French (fr)', 'English (en)'.",
        "placeholders": ["voice_ref", "text", "language", "exaggeration", "seed", "name"],
        "files": {"voice_ref": "the character's locked voice reference (wav, 5-10 s)"},
        "defaults": {"language": "French (fr)", "exaggeration": 0.5},
        "requires": [],
        "output_node": "save",
        "graph": g,
    }


TEMPLATES = {
    "ltx25_i2v_speech": ltx25_i2v_speech,
    "ltx25_a2v_speech": ltx25_a2v_speech,
    "ltx23_idlora_speech": ltx23_idlora_speech,
    "tts_chatterbox_line": tts_chatterbox_line,
}


def main() -> None:
    for name, build in TEMPLATES.items():
        path = os.path.join(HERE, f"{name}.json")
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(build(), fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        print("wrote", path)


if __name__ == "__main__":
    main()
