"""Build the showrunner ComfyUI workflow templates (API format) from Python.

The JSON files next to this script are generated by ``python -m showrunner.workflows._build``;
edit this file, not the JSON. Each template follows the repo's ``comfy_workflow_v1`` shape
(``graph`` in ComfyUI API format, literal inputs replaced by ``{{placeholders}}``) plus:

- ``files``: placeholders that name an uploaded input file (image, audio);
- ``derived``: placeholders the renderer computes (``frames``, ``half_width`` ...), see
  :mod:`showrunner.comfy_templates`;
- ``output_node`` / ``last_frame_node``: where the clip and its last frame come out.

Sources (read 2026-10-08):
- ``ltx25_i2v_speech``: Comfy-Org/workflow_templates ``video_ltx2_5_i2v.json`` (subgraph flattened).
- ``t2i_flux2_klein`` / ``edit_flux2_klein_multiref``: FLUX.2 [klein] 4B, 4 steps, cfg 1.0 (verified live in
  2026-10); the four reference slots are file placeholders ``ref1``..``ref4``.
- ``vc_chatterbox``: ComfyUI_Fill-ChatterBox voice conversion (the pack pinned in docker/worker-comfyui-tts).

The audio-to-video, ID-LoRA and TTS-line templates tested in plan 36 stage 0 were removed with the old code
(2026-10-09): D7 chose LTX-2.5 picture-and-voice; git history keeps them.

Every node class used here exists in ComfyUI 0.34.0 (the version pinned by worker-comfyui
5.10.0); ``showrunner/tools/validate_workflows.py`` checks that against the ComfyUI source.
"""

from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Distilled schedules of the official templates.
SIGMAS_8_STEP = "1.0, 0.99375, 0.9875, 0.98125, 0.975, 0.909375, 0.725, 0.421875, 0.0"
SIGMAS_STAGE2_I2V = "0.85, 0.7250, 0.4219, 0.0"          # LTX-2.5 I2V template

NEGATIVE_DEFAULT = ("live action, real people, photograph, human skin, mask, costume, "
                    "blurry, deformed mouth, extra limbs, text, subtitles, watermark, pc game, "
                    "console game, video game, childish, ugly")

LTX25 = {
    "unet": "ltx-2.5-22b-distilled-transformer-comfy-int8-convrot.safetensors",
    "clip": "gemma4-12b-with-proj-ltx-2.5-comfy-int8-convrot.safetensors",
    "vae": "ltx-2.5-video-vae-bf16.safetensors",
    "audio_vae": "ltx-2.5-audio-vae-bf16.safetensors",
    "upscaler": "ltx-2.5-latent-spatial-upscaler-x2-bf16-1.0.safetensors",
}


def node(class_type: str, **inputs) -> dict:
    return {"class_type": class_type, "inputs": inputs}


def link(node_id: str, slot: int = 0) -> list:
    return [node_id, slot]


# ----------------------------------------------------------------- shared blocks

def _image_in(graph: dict) -> None:
    """LoadImage -> ImageScale (center crop to the clip size) -> LTXVPreprocess."""
    graph["image"] = node("LoadImage", image="{{image}}")
    graph["scale"] = node("ImageScale", image=link("image"), upscale_method="lanczos",
                          width="{{width}}", height="{{height}}", crop="center")
    graph["prep"] = node("LTXVPreprocess", image=link("scale"), img_compression=18)


def _video_out(graph: dict, vae: list, audio: list, *, tiled=(512, 64, 64, 16)) -> None:
    """VAEDecodeTiled -> CreateVideo(+audio) -> SaveVideo (mp4/h264), plus the last frame as PNG.

    Core ``SaveVideo`` reports its file under the ``images`` history key, the only key the
    stock worker-comfyui handler returns; ``SaveImage`` of the last frame arrives in the
    same array (used as the continuity reference of the next shot).
    """
    tile_size, overlap, temporal_size, temporal_overlap = tiled
    graph["dec"] = node("VAEDecodeTiled", samples=link("sep2"), vae=vae, tile_size=tile_size, overlap=overlap,
                        temporal_size=temporal_size, temporal_overlap=temporal_overlap)
    graph["video"] = node("CreateVideo", images=link("dec"), fps="{{fps}}", audio=audio)
    graph["save"] = {"class_type": "SaveVideo",
                     "inputs": {"video": link("video"), "filename_prefix": "showrunner/{{name}}",
                                "format": "mp4", "format.codec": "h264"}}
    graph["last"] = node("ImageFromBatch", image=link("dec"), batch_index="{{last_index}}", length=1)
    graph["save_last"] = node("SaveImage", images=link("last"), filename_prefix="showrunner/{{name}}_last")


def _two_stage(graph: dict, *, model1: list, model2: list, pos1: list, neg1: list, pos2: list, neg2: list,
               vae: list, audio_latent1: list, audio_latent2, guider: str, sampler: str,
               sigmas2: str, cfg_inputs: dict) -> None:
    """Stage 1 at half size (8 distilled steps) -> x2 latent upsampler -> stage 2 (3 steps).

    ``audio_latent2`` is a link, or ``"stage1"`` to reuse the audio latent stage 1 produced.
    """
    graph["lat1"] = node("EmptyLTXVLatentVideo", width="{{half_width}}", height="{{half_height}}",
                         length="{{frames}}", batch_size=1)
    graph["i2v1"] = node("LTXVImgToVideoInplace", vae=vae, image=link("prep"), latent=link("lat1"),
                         strength=0.7, bypass=False)
    graph["cat1"] = node("LTXVConcatAVLatent", video_latent=link("i2v1"), audio_latent=audio_latent1)
    graph["guider1"] = node(guider, model=model1, positive=pos1, negative=neg1, **cfg_inputs)
    graph["noise1"] = node("RandomNoise", noise_seed="{{seed}}")
    graph["sampler"] = node("KSamplerSelect", sampler_name=sampler)
    graph["sig1"] = node("ManualSigmas", sigmas=SIGMAS_8_STEP)
    graph["s1"] = node("SamplerCustomAdvanced", noise=link("noise1"), guider=link("guider1"),
                       sampler=link("sampler"), sigmas=link("sig1"), latent_image=link("cat1"))
    graph["sep1"] = node("LTXVSeparateAVLatent", av_latent=link("s1"))
    graph["ups"] = node("LTXVLatentUpsampler", samples=link("sep1", 0), upscale_model=link("up_model"), vae=vae)
    graph["i2v2"] = node("LTXVImgToVideoInplace", vae=vae, image=link("prep"), latent=link("ups"),
                         strength=1.0, bypass=False)
    graph["cat2"] = node("LTXVConcatAVLatent", video_latent=link("i2v2"),
                         audio_latent=link("sep1", 1) if audio_latent2 == "stage1" else audio_latent2)
    graph["guider2"] = node(guider, model=model2, positive=pos2, negative=neg2, **cfg_inputs)
    graph["noise2"] = node("RandomNoise", noise_seed=42)
    graph["sig2"] = node("ManualSigmas", sigmas=sigmas2)
    graph["s2"] = node("SamplerCustomAdvanced", noise=link("noise2"), guider=link("guider2"),
                       sampler=link("sampler"), sigmas=link("sig2"), latent_image=link("cat2"))
    graph["sep2"] = node("LTXVSeparateAVLatent", av_latent=link("s2"))


def _ltx25_loaders(graph: dict) -> None:
    graph["unet"] = node("UNETLoader", unet_name=LTX25["unet"], weight_dtype="default")
    graph["vae"] = node("VAELoader", vae_name=LTX25["vae"])
    graph["avae"] = node("VAELoader", vae_name=LTX25["audio_vae"])
    graph["clip"] = node("CLIPLoader", clip_name=LTX25["clip"], type="ltxv", device="default")
    graph["up_model"] = node("LatentUpscaleModelLoader", model_name=LTX25["upscaler"])
    graph["pos"] = node("CLIPTextEncode", text="{{prompt}}", clip=link("clip"))
    graph["neg"] = node("CLIPTextEncode", text="{{negative}}", clip=link("clip"))
    graph["cond"] = node("LTXVConditioning", positive=link("pos"), negative=link("neg"), frame_rate="{{fps}}")


def _template(name: str, task: str, description: str, graph: dict, placeholders: list, files: dict,
              requires: list, **extra) -> dict:
    tpl = {
        "$schema": "comfy_workflow_v1",
        "name": name,
        "task": task,
        "core_nodes_only": extra.pop("core_nodes_only", True),
        "verified_live": False,
        "description": description,
        "placeholders": placeholders,
        "files": files,
        "derived": {"frames": "1 + floor(fps * seconds / 8) * 8", "half_width": "width / 2",
                    "half_height": "height / 2", "last_index": "frames - 1"},
        "defaults": {"width": 704, "height": 1280, "fps": 24, "seconds": 5, "negative": NEGATIVE_DEFAULT},
        "frame_rule": {"fps": 24, "frame_step": 8, "max_frames": 241, "lengths": [5, 6, 8, 10]},
        "requires": requires,
        "output_node": "save",
        "last_frame_node": "save_last",
        "graph": graph,
    }
    tpl.update(extra)
    return tpl


def _req(node_id: str, field: str, file: str, folder: str) -> dict:
    return {"node": node_id, "field": field, "file": file, "dir": f"models/{folder}"}


# ----------------------------------------------------------------- the four templates

def ltx25_i2v_speech() -> dict:
    """Path (a): LTX-2.5 image-to-video, dialogue spoken from the prompt alone (joint audio)."""
    g: dict = {}
    _image_in(g)
    _ltx25_loaders(g)
    g["alat"] = node("LTXVEmptyLatentAudio", audio_vae=link("avae"), frames_number="{{frames}}",
                     frame_rate="{{fps}}", batch_size=1)
    _two_stage(g, model1=link("unet"), model2=link("unet"), pos1=link("cond", 0), neg1=link("cond", 1),
               pos2=link("cond", 0), neg2=link("cond", 1), vae=link("vae"), audio_latent1=link("alat"),
               audio_latent2="stage1", guider="LTXVDualCFGGuider", sampler="euler_ancestral",
               sigmas2=SIGMAS_STAGE2_I2V, cfg_inputs={"video_cfg": 1.0, "audio_cfg": 1.0})
    g["adec"] = node("LTXVAudioVAEDecode", samples=link("sep2", 1), audio_vae=link("avae"))
    _video_out(g, vae=link("vae"), audio=link("adec"))
    return _template(
        "ltx25_i2v_speech", "i2v_speech",
        "LTX-2.5 22B distilled int8, two-stage (8 steps at half size, x2 latent upscale, 3 steps), "
        "24 fps, joint audio: the character speaks the quoted line of the prompt with a voice the prompt "
        "describes. The clip is saved WITH its sound (mp4/h264+aac) and its last frame as PNG. "
        "Authored from ComfyUI's video_ltx2_5_i2v.json (2026-10-08), subgraph flattened, prompt "
        "enhancer dropped. Only core nodes of ComfyUI 0.34.0.",
        g, ["image", "prompt", "negative", "seed", "width", "height", "seconds", "fps", "name"],
        {"image": "the keyframe (png), uploaded as input.images[].name"},
        [_req("unet", "unet_name", LTX25["unet"], "diffusion_models"),
         _req("clip", "clip_name", LTX25["clip"], "text_encoders"),
         _req("vae", "vae_name", LTX25["vae"], "vae"),
         _req("avae", "vae_name", LTX25["audio_vae"], "vae"),
         _req("up_model", "model_name", LTX25["upscaler"], "latent_upscale_models")],
    )


def vc_chatterbox() -> dict:
    """Voice conversion (plan 36 stage 1.0, A-221): the audio of a clip re-voiced as the character's
    locked voice, timing kept, so the clip's lips stay in sync. ``FL_ChatterboxVC`` of the pinned
    Fill-ChatterBox pack (inputs ``input_audio``, ``target_voice``, ``seed``); its weights load from
    ``models/chatterbox/chatterbox_vc/`` (``s3gen.pt``, ``conds.pt``), downloaded at first use if absent.
    """
    g: dict = {}
    g["source"] = node("LoadAudio", audio="{{input}}")
    g["target"] = node("LoadAudio", audio="{{target_voice}}")
    g["vc"] = node("FL_ChatterboxVC", input_audio=link("source"), target_voice=link("target"), seed="{{seed}}",
                   use_cpu=False, keep_model_loaded=True)
    g["save"] = node("SaveAudio", audio=link("vc", 0), filename_prefix="showrunner/{{name}}")
    return {
        "$schema": "comfy_workflow_v1",
        "name": "vc_chatterbox",
        "task": "voice_conversion",
        "core_nodes_only": False,
        "custom_nodes": ["comfyui_fill-chatterbox"],
        "verified_live": False,
        "description": "Chatterbox voice conversion: the uploaded speech (`input`, the audio of a clip) re-voiced "
                       "with the timbre of `target_voice` (the character's locked reference, 5-10 s), timing kept. "
                       "Saved as flac by core SaveAudio and returned under the `audio` key by the repo's patched "
                       "worker handler. The node downloads ResembleAI/chatterbox s3gen.pt + conds.pt into "
                       "models/chatterbox/chatterbox_vc/ at first use if they are not on the volume.",
        "placeholders": ["input", "target_voice", "seed", "name"],
        "files": {"input": "the speech to convert (wav)",
                  "target_voice": "the character's locked voice reference (wav, 5-10 s)"},
        "defaults": {"seed": 0},
        "requires": [],
        "output_node": "save",
        "graph": g,
    }


FLUX2_KLEIN = {"unet": "flux-2-klein-4b.safetensors", "clip": "qwen_3_4b.safetensors", "vae": "flux2-vae.safetensors"}
REF_SLOTS = 4


def _flux2_klein(g: dict, positive: list) -> None:
    """Loaders + sampler + decode + save of the FLUX.2 [klein] graphs (node ids of the app's templates)."""
    g["5"] = node("EmptySD3LatentImage", width="{{width}}", height="{{height}}", batch_size=1)
    g["3"] = node("KSampler", seed="{{seed}}", steps=4, cfg=1.0, sampler_name="euler", scheduler="simple",
                  denoise=1.0, model=link("10"), positive=positive, negative=link("7"), latent_image=link("5"))
    g["8"] = node("VAEDecode", samples=link("3"), vae=link("12"))
    g["9"] = node("SaveImage", filename_prefix="showrunner/{{name}}", images=link("8"))


def _flux2_loaders(g: dict) -> None:
    g["10"] = node("UNETLoader", unet_name=FLUX2_KLEIN["unet"], weight_dtype="default")
    g["11"] = node("CLIPLoader", clip_name=FLUX2_KLEIN["clip"], type="flux2", device="default")
    g["12"] = node("VAELoader", vae_name=FLUX2_KLEIN["vae"])
    g["6"] = node("CLIPTextEncode", text="{{prompt}}", clip=link("11"))
    g["7"] = node("CLIPTextEncode", text="{{negative}}", clip=link("11"))


def _image_template(name: str, task: str, description: str, graph: dict, placeholders: list, files: dict) -> dict:
    return {
        "$schema": "comfy_workflow_v1",
        "name": name,
        "task": task,
        "core_nodes_only": True,
        "verified_live": False,
        "description": description,
        "placeholders": placeholders,
        "files": files,
        "defaults": {"width": 832, "height": 1216, "negative": ""},
        "requires": [_req("10", "unet_name", FLUX2_KLEIN["unet"], "diffusion_models"),
                     _req("11", "clip_name", FLUX2_KLEIN["clip"], "text_encoders"),
                     _req("12", "vae_name", FLUX2_KLEIN["vae"], "vae")],
        "output_node": "9",
        "graph": graph,
    }


def t2i_flux2_klein() -> dict:
    """Text to image (cast full-body candidates, keyframes without references)."""
    g: dict = {}
    _flux2_loaders(g)
    _flux2_klein(g, positive=link("6"))
    return _image_template(
        "t2i_flux2_klein", "t2i",
        "Text to image on FLUX.2 [klein] 4B (4 steps, cfg 1.0: the negative is ignored, say it in the positive). "
        "A copy of the app's verified-live t2i_flux2_klein graph; only the output prefix differs.",
        g, ["prompt", "negative", "seed", "width", "height", "name"], {})


def edit_flux2_klein_multiref() -> dict:
    """Image edit with up to four references chained as ReferenceLatent (cast turnaround, emotion grid,
    keyframes from the cast's canonical images and a place plate)."""
    g: dict = {}
    _flux2_loaders(g)
    prev = link("6")
    for k in range(REF_SLOTS):
        # The app's copy also sets upload="image", a UI widget hint LoadImage does not declare (ignored).
        g[str(20 + k)] = node("LoadImage", image=f"{{{{ref{k + 1}}}}}")
        g[str(30 + k)] = node("VAEEncode", pixels=link(str(20 + k)), vae=link("12"))
        g[str(40 + k)] = node("ReferenceLatent", conditioning=prev, latent=link(str(30 + k)))
        prev = link(str(40 + k))
    _flux2_klein(g, positive=prev)
    return _image_template(
        "edit_flux2_klein_multiref", "edit",
        "Image edit on FLUX.2 [klein] 4B with four reference slots (ref1..ref4), each encoded and chained as a "
        "ReferenceLatent conditioning; fewer references repeat the last one "
        "(showrunner.comfy_templates.multiref_files). A copy of the app's verified-live "
        "edit_flux2_klein_multiref graph; only the output prefix and the slot placeholders differ.",
        g, ["prompt", "negative", "seed", "width", "height", "name", "ref1", "ref2", "ref3", "ref4"],
        {f"ref{k + 1}": f"reference image {k + 1} (png)" for k in range(REF_SLOTS)})


TEMPLATES = {
    "ltx25_i2v_speech": ltx25_i2v_speech,
    "vc_chatterbox": vc_chatterbox,
    "t2i_flux2_klein": t2i_flux2_klein,
    "edit_flux2_klein_multiref": edit_flux2_klein_multiref,
}


def main() -> None:
    for name, build in TEMPLATES.items():
        path = os.path.join(HERE, f"{name}.json")
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(build(), fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        print("wrote", path)


if __name__ == "__main__":
    main()
